conversation---
title: 'Identifying Patterns and Biases in Film Dialogues_PatternsInFilmDialogues_As-Predicted_PreReg#'
output: pdf_document
---

##Authors

Example:
Ankit Saxena *(University of Pennsylvania) - asaxena7@sas.upenn.edu*

## Name
Identifying Patterns and Biases in Film Dialogues

***

## Research goal and rationale
  Effective dialogue between movie characters is one of the most important tools a filmmaker has to communicate the vision of their movie, move the plot forward, and engage the audience. These dialogues are not only a reflection of how screenwriters view different types of people, but they also influence the audience's perception of these groups. In this paper, we hope to uncover these qualitative and quantitative patterns and objectively identify any biases, particularly gender-related biases, that may be prevalent in popular culture.


## Hypotheses
  H1: Men tend to have more dialogues than women.
  H2: Men are usually the first to start a conversation.


## Data collection
  Have any data been collected for this study already?

> Yes, we already collected the data.

#### Dependent variables
  Describe the key dependent variable(s) specifying how they will be measured.

> Length of a dialogue
> Gender of person who starts a conversation


#### Conditions
  How many and which conditions will participants be assigned to?

> The secondary data already contains all conversations between movie characters.


#### Outliers and Exclusions
Describe exactly how outliers will be defined and handled, and your precise rule(s) for excluding observations.

> All conversations with which are from a film with less than 5 IMDB ratings have been excluded
> Conversations which contain words that cannot be matched in a dictionary will be manually checked before including in an analysis. If there is a spelling mistake, then it will be manually corrected after verifying from the original source


#### Sample Size
How many observations will be collected or what will determine sample size?

> The secondary data collected already has 220,579 conversational exchanges between 9,035 characters from 617 movies.
